### ISSUE TITLE
Bottle store max

### ISSUE THREAD

**Issue by hotspuraz** [Zrips/BottledExp#11]
The /bottle store max command is no longer working since the most recent update. 

![image](https://user-images.githubusercontent.com/38726257/116259461-b97a3580-a76d-11eb-9a1c-2082020fc47a.png)

**Comment by Titigre** [comment]
Yes same here, hope they will fix it soon

**Comment by Strahilchu** [comment]
Also having this issue, was about to post but I saw this.
Zrips please fix :)

**Comment by Zrips** [comment]
Fixed
