### ISSUE TITLE
Clicking on Blocks doesn't work in Adventure Mode

### ISSUE THREAD

**Issue by Kruize1** [Zrips/BottledExp#13]
1. Install Plugin
2. Enable and Place Enchanting Tables
3. Left click on Enchanting Table
4. Note: Nothing happens
5. Switch to Survival and note it does work

**Comment by Zrips** [comment]
This is due to a bug with Minecraft itself not returning the block which was interacted with a left-click while you are in adventure mode. Can't do anything with that.
