### ISSUE TITLE
free xp

### ISSUE THREAD

**Issue by elaineandsparky** [Zrips/BottledExp#20]
2 issues here which i'm sure are only since the last update but I could be wrong.

doing the command /bottle get (amount) doesn't consume exp or bottles and neither does clicking on an enchant table with an empty bottle, it just gives xp bottles and doesn't take from your xp so free and unlimited exp.

All players have access to all commands by default including /bottle get which i'm sure never used to be the case. We have worked around this by negating all command perms then giving the interact command at the rank we want them to be able to bottle xp at. But it seems a bit odd that it is set this way by default.

However, i'm stuck for how to fix using an emtpy glass bottle on enchant table not using players xp or the bottles in their inventory.

https://pastebin.com/tB3TxBaB

**Comment by Zrips** [comment]
You kind of need to provide atleast server version so we could know basic information where it fails.

**Comment by elaineandsparky** [comment]
1.17.1

**Comment by Zrips** [comment]
Well... You do have this in config file
`  xpCost: 0`
This basically means that the player will spend 0 to get 50 exp, change it to something more appropriate which should be equal or higher than xpEarn and I will add fail safe with next version to prevent situations like this one.

**Comment by elaineandsparky** [comment]
sorry i didn't notice that. It has fixed that issue however it is still not consuimng glass bottles from a players inventory. I'm not sure if this has always been the case or not.

**Comment by Zrips** [comment]
Again, you have this
`  useItems: false`
set it to true and it should work as expected.
