### ISSUE TITLE
Made a locale for Simplified Chinese (ZHCN)

### ISSUE THREAD

**Issue by ChromaPIE** [Zrips/BottledExp#21]
Seems like the project is not maintained here anymore but I'll just let it be here. The locale is available here: https://github.com/ChromaPIE/chromic-plugin-locale-bundle/blob/overlord/plugins/BottledExp/Locale_CN.yml

I'll be appreciated if it's gonna be in the next update. Thank you!

**Comment by Zrips** [comment]
Will add with next update. Thanks for translation.

**Comment by ChromaPIE** [comment]
I noticed that Line 11 has been changed and formatted, causing a fallback to English. Already fixed that in the link above. Might not be a big deal so if there's an update in the future, it'd be great to include the fix!
