### ISSUE TITLE
add config instead of xp make the level

### ISSUE THREAD

**Issue by Krivakor** [Zrips/BottledExp#22]
add please config (show not EXP but LVL)
![image](https://user-images.githubusercontent.com/60703928/137133492-4608341f-3344-4f20-a83a-47ac9ce4f9b9.png)

**Comment by Krivakor** [comment]
P.S I use Google translate, sorry

**Comment by Zrips** [comment]
Level is not linear, which means that if you are at level 1 and you have this 30970 it might add you extra 30 levels, but if you are at level 30 and you have same amount of exp it might only add 1-2 levels. So its not really that useful to identify how many levels it will be when its all dependent on your own current level.

**Comment by Krivakor** [comment]
> Level is not linear, which means that if you are at level 1 and you have this 30970 it might add you extra 30 levels, but if you are at level 30 and you have same amount of exp it might only add 1-2 levels. So its not really that useful to identify how many levels it will be when its all dependent on your own current level.

add lore [experience {lvl} - {exp}]

**Comment by Zrips** [comment]
Added
