### ISSUE TITLE
Suggest 

### ISSUE THREAD

**Issue by Immersio36** [Zrips/BottledExp#32]
I have an idea of ​​adding bottle xp, I don't know if it's possible but make sure that by mining or other we can fill bottles with the xp obtained

**Comment by Zrips** [comment]
This should be handled by more specialized plugins like JobsReborn which can grant you exp points for wide range of actions which then you could use to fill up your exp bottles. It would be to big of a feature to start adding as this will blow up into huge requirements by people to handle dozens of different actions differently and different rewards for different blocks, which again, is being handled quite well by JobsReborn plugin
