### ISSUE TITLE
XP is not being converted to the right amount of bottles.

### ISSUE THREAD

**Issue by Smudgge** [Zrips/BottledExp#38]
# How to replicate the bug
Regenerate the plugins configs `(BottledExp 3.1.3.0)`
Fill your inventory with items and leave 1 slot empty.
Give your self 100 levels. `/xp set 100l`
Run the command `/bottle get max`

You only get 1 stack of bottles, and your levels disappear.

# Possible fixes
Create an option in the configuration that when set to true, the command only takes as much xp as it can give.

**Comment by Zrips** [comment]
Will be fixed with next update
