### ISSUE TITLE
Bug: Locale_DE.yml resets after restart

### ISSUE THREAD

**Issue by PanetiX** [Zrips/BottledExp#40]
Hello,
i have made some changes in the Locale_DE.yml but after a server restart the langfile will be resetted.
When i upload my changed file again after a restart and use command /bottle reload it works. Only after restart the file will be resetted.

**This i s my Locale_DE.yml:** https://pastebin.com/wjkYtC9A

**Comment by Zrips** [comment]
Tested your locale with basic reload and server restart, everything looks to be working and no detectable issues with it. Changes remain as they are defined. Does this happen with EN locale or is this only with DE one?
