### ISSUE TITLE
experience bottles lag

### ISSUE THREAD

**Issue by ava852546** [Zrips/BottledExp#54]
https://youtu.be/DJ0jGTPMAv4
When I use the [/bottle get max] command, the server produces a large number of experience bottles, especially when I have a very high level (e.g., 1000L). This causes lag on both the server and client.
BottledExp-3.2.2.5
CMILib1.4.7.3
Current: git-Purpur-2176 (MC: 1.20.4)

**Comment by Zrips** [comment]
Will make a hard limit for this command, as it should not spawn it so many bottles at once
