### ISSUE TITLE
EXP Loss when inventory is full.

### ISSUE THREAD

**Issue by InventiveSins** [Zrips/BottledExp#57]
When your inventory is full, and you store EXP into a bottle, the bottle disappears. I also tried this with a full inventory but with one slot with just one bottle, and even then, the exp gets stored into the bottle which instantly disappears. 

Video: https://gyazo.com/1bda6e89b15d0f95718a7864feb4a8f9

Server Ver: Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)

CMI: CMILib1.4.7.16.jar
BottledEXP: BottledExp-3.2.2.7.jar

**Comment by DimaSergeew** [comment]
I have the same problem with the latest version of the plugin.

**Comment by Zrips** [comment]
Should be fixed with next update
