### ISSUE TITLE
Duplication Bug: Full Inventory of Experience Bottles with Specific Commands

### ISSUE THREAD

**Issue by DimaSergeew** [Zrips/BottledExp#58]
I found a dupe in the plugin: if you have level 10 and enter the command /bottle store max 6000, you get a full inventory of experience bottles. This issue also occurs with the command /bottle store max 1L 6000.
Steps to reproduce:

1. Reach level 10.
2. Enter the command /bottle store max 6000.
3. Observe the inventory filled with experience bottles.

This bug significantly impacts gameplay by allowing unintended duplication of experience bottles.

**Comment by DimaSergeew** [comment]
I checked all versions, and found that in time 3.2.2.2.4 this duping appeared.

**Comment by Zrips** [comment]
Should be fixed with next version
