### ISSUE TITLE
language message in the get command missing

### ISSUE THREAD

**Issue by Sulort** [Zrips/BottledExp#9]
Hi, 
for the **bottle get max** command you are using the same language message (command.get.info.noExp) for three different calculated amount values. (amount of XP, Items and Money) But there are three different language messages.
Could you please differentiate between these three amounts and send the individul language message to the player, as you are doing in the **bottle store max** command.

And there are some debug messages in the **bottle store max** command. Maybee also somewhere else.
![](https://i.gyazo.com/thumb/1200/7b7a96d7903e5a1d22d58c6b53c15216-png.jpg)

---

**Server Type:** Paperspigot

**Server Version:** papermc 1.16.3 version 195

**Plugin Version:** BottledExp2.2.8.1

**Comment by Sulort** [comment]
this issue with the language message is still alive in the latest version BottledExp 3.0.0.0

is it possible to fix it please.
thanks a lot

**Comment by Zrips** [comment]
Will add with next build
